androdeb: fix incorrect home directory variable
The following command fails on androdeb.

The output looks like:
curl https://sh.rustup.rs -sSf | sh
info: downloading installer
error: $HOME differs from euid-obtained home directory: you may be using sudo
error: if this is what you want, restart the installation with `-y'

This is because home directory wasn't set.

Signed-off-by: Joel Fernandes <joel@joelfernandes.org>